<?php

$cont = <<<APMUTHU

APMUTHU;


$cont = str_replace('\040',' ', $cont);
$cont = str_replace('\041','!', $cont);
$cont = str_replace('\042','"', $cont);
$cont = str_replace('\043','#', $cont);
$cont = str_replace('\044','$', $cont);
$cont = str_replace('\045','%', $cont);
$cont = str_replace('\046','&', $cont);
$cont = str_replace('\047',"'", $cont);
$cont = str_replace('\050','(', $cont);
$cont = str_replace('\051',')', $cont);
$cont = str_replace('\052','*', $cont);
$cont = str_replace('\053','+', $cont);
$cont = str_replace('\054',',', $cont);
$cont = str_replace('\055','-', $cont);
$cont = str_replace('\056','.', $cont);
$cont = str_replace('\057','/', $cont);
$cont = str_replace('\060','0', $cont);
$cont = str_replace('\061','1', $cont);
$cont = str_replace('\062','2', $cont);
$cont = str_replace('\063','3', $cont);
$cont = str_replace('\064','4', $cont);
$cont = str_replace('\065','5', $cont);
$cont = str_replace('\066','6', $cont);
$cont = str_replace('\067','7', $cont);
$cont = str_replace('\070','8', $cont);
$cont = str_replace('\071','9', $cont);
$cont = str_replace('\072',':', $cont);
$cont = str_replace('\073',';', $cont);
$cont = str_replace('\074','<', $cont);
$cont = str_replace('\075','=', $cont);
$cont = str_replace('\076','>', $cont);
$cont = str_replace('\077','?', $cont);
$cont = str_replace('\100','@', $cont);
$cont = str_replace('\101','A', $cont);
$cont = str_replace('\102','B', $cont);
$cont = str_replace('\103','C', $cont);
$cont = str_replace('\104','D', $cont);
$cont = str_replace('\105','E', $cont);
$cont = str_replace('\106','F', $cont);
$cont = str_replace('\107','G', $cont);
$cont = str_replace('\110','H', $cont);
$cont = str_replace('\111','I', $cont);
$cont = str_replace('\112','J', $cont);
$cont = str_replace('\113','K', $cont);
$cont = str_replace('\114','L', $cont);
$cont = str_replace('\115','M', $cont);
$cont = str_replace('\116','N', $cont);
$cont = str_replace('\117','O', $cont);
$cont = str_replace('\120','P', $cont);
$cont = str_replace('\121','Q', $cont);
$cont = str_replace('\122','R', $cont);
$cont = str_replace('\123','S', $cont);
$cont = str_replace('\124','T', $cont);
$cont = str_replace('\125','U', $cont);
$cont = str_replace('\126','V', $cont);
$cont = str_replace('\127','W', $cont);
$cont = str_replace('\130','X', $cont);
$cont = str_replace('\131','Y', $cont);
$cont = str_replace('\132','Z', $cont);
$cont = str_replace('\133','[', $cont);
$cont = str_replace('\135',']', $cont);
$cont = str_replace('\136','^', $cont);
$cont = str_replace('\137','_', $cont);
$cont = str_replace('\140','`', $cont);
$cont = str_replace('\141','a', $cont);
$cont = str_replace('\142','b', $cont);
$cont = str_replace('\143','c', $cont);
$cont = str_replace('\144','d', $cont);
$cont = str_replace('\145','e', $cont);
$cont = str_replace('\146','f', $cont);
$cont = str_replace('\147','g', $cont);
$cont = str_replace('\150','h', $cont);
$cont = str_replace('\151','i', $cont);
$cont = str_replace('\152','j', $cont);
$cont = str_replace('\153','k', $cont);
$cont = str_replace('\154','l', $cont);
$cont = str_replace('\155','m', $cont);
$cont = str_replace('\156','n', $cont);
$cont = str_replace('\157','o', $cont);
$cont = str_replace('\160','p', $cont);
$cont = str_replace('\161','q', $cont);
$cont = str_replace('\162','r', $cont);
$cont = str_replace('\163','s', $cont);
$cont = str_replace('\164','t', $cont);
$cont = str_replace('\165','u', $cont);
$cont = str_replace('\166','v', $cont);
$cont = str_replace('\167','w', $cont);
$cont = str_replace('\170','x', $cont);
$cont = str_replace('\171','y', $cont);
$cont = str_replace('\172','z', $cont);
$cont = str_replace('\173','{', $cont);
$cont = str_replace('\174','|', $cont);
$cont = str_replace('\175','}', $cont);
$cont = str_replace('\134','\\', $cont);

echo $cont;

?>
