/*
MySQL - 5.5.36 : Database - ship
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `eta_etd`;
DROP TABLE IF EXISTS `vessel`;

CREATE TABLE `eta_etd` (
  `TRANSID` varchar(25) NOT NULL,
  `VCN` varchar(14) NOT NULL,
  `ETA` datetime DEFAULT NULL,
  `ETD` datetime DEFAULT NULL,
  `ETB` datetime DEFAULT NULL,
  `DRAFT_AFT` float(7,2) DEFAULT NULL,
  `DRAFT_FWD` float(7,2) DEFAULT NULL,
  `FREE_BOARD_AFT_DRAFT` float(7,2) DEFAULT NULL,
  `FREE_BOARD_FWD_DRAFT` float(7,2) DEFAULT NULL,
  `SAILING_AFT_DRAFT` float(7,2) DEFAULT NULL,
  `SAILING_FWD_DRAFT` float(7,2) DEFAULT NULL,
  `REASON_OF_REQUEST` varchar(100) DEFAULT NULL,
  `REASON_OF_RESPONSE` varchar(100) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `CREATED_BY` varchar(35) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(35) DEFAULT NULL,
  `APPROVED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`TRANSID`,`VCN`),
  KEY `CREATED_BY_IDX` (`CREATED_BY`),
  KEY `INDEX_ETA_ETD` (`CREATED_DATE`,`VCN`),
  KEY `VCN_IDX` (`VCN`,`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

CREATE TABLE `vessel` (
  `IMO_NUMBER` varchar(10) NOT NULL,
  `VES_TRANS_ID` varchar(25) DEFAULT NULL,
  `MESSAGE_TYPE` varchar(1) DEFAULT NULL,
  `VESSEL_NAME` varchar(35) DEFAULT NULL,
  `CALL_SIGN` varchar(10) DEFAULT NULL,
  `AGENCY_CODE` varchar(16) DEFAULT NULL,
  `AGENCY_FUNCTION_CODE` varchar(3) DEFAULT NULL,
  `PREV_VESSEL_NAME` varchar(35) DEFAULT NULL,
  `PREV_CALL_SIGN` varchar(10) DEFAULT NULL,
  `VESSEL_FLAG` varchar(2) DEFAULT NULL,
  `SATELLITE_ID` varchar(20) DEFAULT NULL,
  `SATCOM_ID` varchar(20) DEFAULT NULL,
  `FREE_BOARD` float(8,2) DEFAULT NULL,
  `VESSEL_HEIGHT` float(6,2) DEFAULT NULL,
  `BEAM` float(6,2) DEFAULT NULL,
  `LOA` float(6,2) DEFAULT NULL,
  `LBP` float(6,2) DEFAULT NULL,
  `MAX_DRAFT` float(6,2) DEFAULT NULL,
  `PARALLEL_BODY_LENGTH` float(8,3) DEFAULT NULL,
  `DISTANCE_BOW` float(6,2) DEFAULT NULL,
  `GRT` float(10,3) DEFAULT NULL,
  `NRT` float(10,3) DEFAULT NULL,
  `DWT` float(10,3) DEFAULT NULL,
  `SUMMER_DEAD_WEIGHT` float(10,3) DEFAULT NULL,
  `TEU_CAPACITY` int(6) DEFAULT NULL,
  `SBT` varchar(1) DEFAULT NULL,
  `REDUCED_GRT` float(10,3) DEFAULT NULL,
  `VESSEL_BUILDING_DATE` datetime DEFAULT NULL,
  `VESSEL_BUILDING_PLACE` varchar(20) DEFAULT NULL,
  `KEEL_LYING` datetime DEFAULT NULL,
  `VESSEL_TYPE` varchar(8) DEFAULT NULL,
  `OWNER_NAME` varchar(35) DEFAULT NULL,
  `VESSEL_EMAIL` varchar(50) DEFAULT NULL,
  `CLASSIFICATION_SOCIETY` varchar(35) DEFAULT NULL,
  `PNI_CLUB` varchar(50) DEFAULT NULL,
  `PNI_INSURANCE_VALID_UPTO` datetime DEFAULT NULL,
  `PNI_CLUB_REPRESENTATIVE` varchar(50) DEFAULT NULL,
  `INSURANCE_COMPANY` varchar(50) DEFAULT NULL,
  `ENGINE_TYPE` varchar(20) DEFAULT NULL,
  `NUMBER_OF_ENGINES` int(2) DEFAULT NULL,
  `ENGINE_POWER` varchar(20) DEFAULT NULL,
  `PROPULSION_TYPE` varchar(35) DEFAULT NULL,
  `NO_OF_PROPELLERS` int(2) DEFAULT NULL,
  `NO_OF_VESSELGEARS` varchar(20) DEFAULT NULL,
  `NO_OF_BAYS` int(2) DEFAULT NULL,
  `NO_OF_DECK_ROWS` int(2) DEFAULT NULL,
  `HATCH_COVER_TYPE` varchar(1) DEFAULT NULL,
  `NO_OF_HATCHES` int(2) DEFAULT NULL,
  `MAX_MANEUVERING_SPEED` float(5,1) DEFAULT NULL,
  `BOW_THRUSTER` varchar(1) DEFAULT NULL,
  `BOW_THRUSTER_NUMBER` int(3) DEFAULT NULL,
  `BOW_THRUSTER_POWER` float(5,1) DEFAULT NULL,
  `STERN_THRUSTER_NUMBER` int(2) DEFAULT NULL,
  `STERN_THRUSTER_POWER` float(5,1) DEFAULT NULL,
  `BULBOUS_BOW` varchar(1) DEFAULT NULL,
  `SR_CERTIFICATE_NO` varchar(35) DEFAULT NULL,
  `SR_VALIDITY_DATE` datetime DEFAULT NULL,
  `SM_CERTIFICATE_NO` varchar(35) DEFAULT NULL,
  `SM_VALIDITY_DATE` datetime DEFAULT NULL,
  `ISPS_COMPLIANCE` varchar(1) DEFAULT NULL,
  `CAPII_CERTIFICATE` varchar(1) DEFAULT NULL,
  `PORT_OF_REGISTRATION` varchar(6) DEFAULT NULL,
  `MMSI_NO` varchar(10) DEFAULT NULL,
  `STATUS` varchar(15) DEFAULT NULL,
  `IS_DRAFT` char(1) DEFAULT NULL,
  `PORT_OF_SUBMISSION` varchar(6) DEFAULT NULL,
  `CREATED_BY` varchar(35) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `INSURANCE_VALIDITY` datetime DEFAULT NULL,
  `OLD_TRANSACTION_ID` varchar(20) DEFAULT NULL,
  `PERMANENT_SHIP_REGISTRATION` varchar(1) DEFAULT NULL,
  `VALIDITY_OF_REGISTRATION` varchar(10) DEFAULT NULL,
  `MTMV` varchar(2) DEFAULT NULL,
  PRIMARY KEY (`IMO_NUMBER`),
  KEY `CREATED_BY_IDX` (`CREATED_BY`),
  KEY `CREATED_DATE_IDX` (`CREATED_DATE`),
  KEY `IDX_VES_TRANS_ID` (`VES_TRANS_ID`),
  KEY `OLD_TRANSACTION_ID_IDX` (`OLD_TRANSACTION_ID`,`VESSEL_NAME`,`STATUS`,`PORT_OF_SUBMISSION`,`MESSAGE_TYPE`),
  KEY `STATUS_IDX` (`STATUS`,`CREATED_DATE`,`PORT_OF_SUBMISSION`,`CREATED_BY`,`CALL_SIGN`),
  KEY `VESSEL_TYPE_IDX` (`VESSEL_TYPE`,`CREATED_BY`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

/*Data for the table `vessel` */

/*Table structure for table `voyage` */

DROP TABLE IF EXISTS `voyage`;

CREATE TABLE `voyage` (
  `VOYAGE_TRANSACTION_ID` varchar(25) NOT NULL DEFAULT '',
  `VOYAGE_NUMBER` varchar(10) DEFAULT NULL,
  `VCN` varchar(14) DEFAULT NULL,
  `PORT_CODE` varchar(6) DEFAULT NULL,
  `IMO_NUMBER` varchar(10) DEFAULT NULL,
  `TRADE_TYPE` char(2) DEFAULT NULL,
  `SHIPPING_AGENT_CODE` varchar(16) DEFAULT NULL,
  `SHIPPING_AGENT_CODE_EX` varchar(16) DEFAULT NULL,
  `SHIPPING_LINE_CODE` varchar(16) DEFAULT NULL,
  `TERMINAL_OPERATOR_CODE` varchar(15) DEFAULT NULL,
  `ETA` datetime DEFAULT NULL,
  `ETD` datetime DEFAULT NULL,
  `SERVICE_NAME` varchar(10) DEFAULT NULL,
  `PORT_OF_DEPARTURE` varchar(6) DEFAULT NULL,
  `LAST_CALL_PORT` varchar(6) DEFAULT NULL,
  `EXPECTED_DRAFT` float(5,2) DEFAULT NULL,
  `VISIT_PURPOSE` varchar(3) DEFAULT NULL,
  `CARGO_TYPE` char(1) DEFAULT NULL,
  `NO_OF_TEUS` float DEFAULT NULL,
  `NO_OF_20F_CONTAINER` float DEFAULT NULL,
  `NO_OF_40F_CONTAINER` float DEFAULT NULL,
  `NO_OF_OTHER_CONTAINER` float DEFAULT NULL,
  `TOTAL_CONTAINER_TONNAGE` float DEFAULT NULL,
  `CARGO_DESCRIPTION` varchar(250) DEFAULT NULL,
  `CARGO_TONNAGE` float(11,2) DEFAULT NULL,
  `VOYAGE_TYPE` varchar(3) DEFAULT NULL,
  `OPERATION_TYPE` varchar(3) DEFAULT NULL,
  `DECK_CARGO` float(6,2) DEFAULT NULL,
  `STATUS` varchar(3) DEFAULT NULL,
  `IN_BALLAST_WITH_CARGO` char(1) DEFAULT NULL,
  `TRADE_CHANGE` varchar(10) DEFAULT NULL,
  `BERTHING` varchar(3) DEFAULT NULL,
  `NAME_OF_CHARTERER` varchar(35) DEFAULT NULL,
  `OIL_CESS_PAID` char(1) DEFAULT NULL,
  `OIL_CESS_PAID_DATE` datetime DEFAULT NULL,
  `OIL_CESS_VALIDITY_DATE` datetime DEFAULT NULL,
  `PORT_OIL_CESS_PAID` varchar(6) DEFAULT NULL,
  `IECODE` varchar(15) DEFAULT NULL,
  `MLO_CODE` varchar(16) DEFAULT NULL,
  `NUM_OF_FENDERS` float DEFAULT NULL,
  `DOUBLE_BANKING` varchar(1) DEFAULT NULL,
  `VESSEL_TYPE` varchar(8) DEFAULT NULL,
  `APPROVAL_STATUS` varchar(1) DEFAULT NULL,
  `DATE_OF_ALLOTMENT` datetime DEFAULT NULL,
  `IS_DRAFT` char(1) DEFAULT NULL,
  `PORT_OF_SUBMISSION` varchar(6) DEFAULT NULL,
  `CREATED_BY` varchar(35) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `BERTH_TYPE` varchar(4) DEFAULT NULL,
  `DUMP_TUG_VESSEL` varchar(1) DEFAULT NULL,
  `VES_TRANS_ID` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`VOYAGE_TRANSACTION_ID`),
  KEY `CREATED_DATE_IDX` (`CREATED_DATE`),
  KEY `IDX_IMO_NO_TPCS_VOY` (`CREATED_BY`),
  KEY `PORT_CODE_IDX` (`VCN`,`PORT_CODE`,`CREATED_BY`,`VES_TRANS_ID`),
  KEY `PORT_OF_SUBMISSION_IDX` (`PORT_OF_SUBMISSION`),
  KEY `VCN_IDX` (`VCN`,`IMO_NUMBER`,`PORT_CODE`,`VOYAGE_NUMBER`,`PORT_OF_SUBMISSION`,`ETA`,`ETD`,`CREATED_DATE`,`APPROVAL_STATUS`,`CREATED_BY`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

/*Data for the table `voyage` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
